server:
  port: 8001

eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://localhost:8000/eureka
  instance:
    # 使用IP地址注册
    prefer-ip-address: true
    # 指定服务的ID
    instance-id: zuul-server:8001

zuul:
  # 禁止使用服务名字进行访问
  ignore-services: "*"
  # 统一前缀
  prefix: "/services"
  # 配置路由
  routes:
    # 指定服务的访问路径
    resources-server-A: "/resources/**"

spring:
  application:
    name: zuul-server
