spring:
  application:
    name: spring-ai
  ai:
    openai:
      base-url: https://api.bianxie.ai
      api-key: "自己的密钥"
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

server:
  port: 9090
