server:
  port: 8004

eureka:
  client:
    # eureka注册中心地址
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    # 使用IP注册
    prefer-ip-address: true
    # 指定服务的ID
    instance-id: resource-server:8004

spring:
  application:
    name: resources-server-A