spring:
  application:
    name: spring-ai
  ai:
    openai:
      base-url: 【你的AI接口地址】
      api-key: 【你的AIkey】
      chat:
        options:
          model: deepseek-chat
          # 值越大，输出结果越随机
          temperature: 0.7
  datasource:
    url: jdbc:mysql://ip:port/ai?defaultFetchSize=50&useCursorFetch=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: user
    password: passwd
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 1234

logging:
  level:
    # 表示AI开启Advisor级别的日志
    org.springframework.ai.chat.client.advisor: debug